[project]
name = "hw2_inbox_impl"
version = "0.1.0"
description = "Gmail client implementation"
requires-python = ">=3.9"

[dependencies]
hw2_inbox_api = { workspace = true }

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[tool.ruff]
line-length = 100

[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "E501",  # Ignore line length issues since no need to go over 100 characters
    "W293", # White spaces are used for indentation in doc strings
    "S101", # Use of assertion should be okay in test files
    "D203", #incompatible with D211 
    "D213", #incompatible with D212
]
fixable = ["ALL"]  # Allow Ruff to auto-fix issues

[tool.uv.sources]
hw2_inbox_api = {workspace = true}

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true
ignore_missing_imports = true  # Ignore missing imports (some external libraries may lack type hints)

[tool.setuptools]
packages = ["src"]
package-dir = {"" = "."}

[tool.pytest.ini_options]
pythonpath = ["."] 