[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "HW1_OSPSD"
version = "0.1.0"
description = "hw1 Calculator"
readme = "README.md"
requires-python = ">=3.9"

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-mock>=3.0.0",
    "mypy>=1.0.0",
    "pytest-cov>=4.1.0",
    "pytest-html>=4.0.0",
    "ruff>=0.3.0",
    "types-setuptools>=42.0.0",
]

[tool.uv.workspace]
members = ["src/calculator", "src/logger", "src/notifier", "tests"]


[tool.ruff.lint]
select = ["ALL"]
ignore = [
    "D203", #incompatible with D211 (D211 suggests no blank line before docstring. D203 suggest a blank line)
    "D213", #incompatible with D212 (D213 suggests multi-line docstrings to start on a new line. D212 requires on the same line.)
]
[tool.ruff.lint.per-file-ignores]
"**/test_*.py" = ["S101", "PLR2004"]  # Allow assertions and magic numbers in test files
fixable = ["ALL"]  # Allow Ruff to auto-fix issues

[tool.setuptools]
packages = ["src", "src.calculator", "src.logger", "src.notifier"]
package-dir = {"" = "."}

[tool.pytest.ini_options]
addopts = "-v"
testpaths = ["tests"]
python_files = ["test_*.py"]
pythonpath = [".", "src"]

[tool.coverage.run]
source = ["src"]

[tool.coverage.html]
directory = "htmlcov"

[tool.coverage.xml]
output = "coverage.xml"

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true
check_untyped_defs = true