version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11  
    working_directory: ~/repo

jobs:
  setup:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install UV Dependency Manager
          command: |
            python -m pip install --upgrade pip
            pip install uv
      - run:
          name: Install Dependencies with UV
          command: |
            uv venv
            uv pip install pytest pytest-cov ruff mypy coverage
      - run:
          name: Verify Installation
          command: |
            uv pip list  # Check installed packages
            uv pip show pytest  # Verify pytest is installed
      - persist_to_workspace:
          root: .
          paths:
            - .venv

  lint-and-static-analysis:
    executor: python-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Run Ruff (Code Formatting and Linting)
          command: |
            uv run ruff check src tests --select ALL
      - run:
          name: Run Mypy (Static Type Checking)
          command: |
            uv run mypy src

  test:
    executor: python-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: 
          name: Verify Virtual Environment Exists
          command: |
            uv pip list  # Ensure pytest is installed
      - run:
          name: Run Unit Tests with Coverage
          command: |
             uv run pytest --cov=src --cov-report=xml --junitxml=test-results/results.xml -v
      - store_test_results:
          path: test-results/
      - store_artifacts:
          path: coverage.xml

  generate-html-coverage-report:
    executor: python-executor
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Generate HTML Coverage Report
          command: |
            uv run pytest --cov=src --cov-report=html -v
      - store_artifacts:
          path: htmlcov/

workflows:
  version: 2.1
  main-workflow:
    jobs:
      - setup
      - lint-and-static-analysis:
          requires:
            - setup
      - test:
          requires:
            - setup
      - generate-html-coverage-report:
          requires:
            - test
