version: 2.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.11  
    working_directory: ~/repo

commands:
  setup-environment:
    steps:
      - checkout
      - run:
          name: Install UV using curl
          command: |
            curl -LsSf https://astral.sh/uv/install.sh | sh
      - run:
          name: Install Project Dependencies
          command: |
            uv venv
            # Install root project dependencies
            uv pip install -e ".[dev]"
            # Install component dependencies
            cd src/calculator && uv pip install -e ".[dev]"
            cd ../logger && uv pip install -e ".[dev]"
            cd ../notifier && uv pip install -e ".[dev]"
            cd ../..
            # Install additional dev dependencies for type checking
            uv pip install types-setuptools>=42.0.0

jobs:
  lint-and-static-analysis:
    executor: python-executor
    steps:
      - setup-environment
      - run:
          name: Run Ruff (Code Formatting and Linting)
          command: |
            uv run ruff check src tests
      - run:
          name: Run Mypy (Static Type Checking)
          command: |
            uv run mypy src

  test:
    executor: python-executor
    steps:
      - setup-environment
      - run:
          name: Run Tests and Generate Coverage
          command: |
            mkdir -p test-results/pytest
            # Using pytest configuration from pyproject.toml
            uv run pytest
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: htmlcov
          destination: coverage-report
      - store_artifacts:
          path: test-results
          destination: test-results

workflows:
  version: 2.1
  main:
    jobs:
      - lint-and-static-analysis
      - test
