[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "integration"
version = "0.1.0"
description = "Integration module for spam detection"
dependencies = [
    "python-dotenv>=1.0.0",
]

[tool.uv.sources]
hw2_inbox_impl = { workspace = true }
ai_conversation_client = {workspace = true}

[tool.pytest.ini_options]
pythonpath = ["."]

[tool.hatch.build.targets.wheel]
packages = ["src/integration"] 